### ISSUE TITLE
[Error] ValueError: not enough values to unpack.

### ISSUE THREAD

**Issue by Icemap** [chineseocr/chineseocr#368] opened 2019-09-25 01:32 UTC
## Trace
> Traceback (most recent call last):
>   File "/Users/cheese/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 257, in process
>     return self.handle()
>   File "/Users/cheese/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 248, in handle
>     return self._delegate(fn, self.fvars, args)
>   File "/Users/cheese/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 488, in _delegate
>     return handle_class(cls)
>   File "/Users/cheese/anaconda3/envs/chineseocr/lib/python3.6/site-packages/web/application.py", line 466, in handle_class
>     return tocall(*args)
>   File "/Users/cheese/Src/PythonSrc/chineseocr/app.py", line 170, in POST
>     rightAdjustAlph=0.01,##对检测的文本行进行向右延伸
>   File "/Users/cheese/Src/PythonSrc/chineseocr/main.py", line 94, in model
>     boxes,scores       = self.box_cluster(img,boxes,scores,**args)
>   File "/Users/cheese/Src/PythonSrc/chineseocr/main.py", line 65, in box_cluster
>     LINE_MIN_SCORE
> ValueError: not enough values to unpack (expected 2, got 0)

## 表现
1. conda安装依赖
2. "python app.py 8080" 启动服务
3. 身份证方式或普通OCR方式都会出现如下报错内容，返回500

**Comment by IT-Xue** [comment] 2020-04-10 05:04
同问

**Comment by IT-Xue** [comment] 2020-04-13 08:32
Duplicate of #359

**Closed as completed** 2020-04-24 09:18 UTC
